const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');
const designs=[...require('./designs-01-03.cjs'),...require('./designs-04-06.cjs'),...require('./designs-07-10.cjs')];
const {pieces,demo,result,modal}=require('./components.cjs');
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const libraries=path.resolve(root,'../LoginDemoCC/assets/libs');
for(const d of designs){const dir=path.join(root,d.id);fs.mkdirSync(path.join(dir,'vendor'),{recursive:true});
 for(const [a,b]of [['bootstrap/bootstrap.min.css','bootstrap.min.css'],['bootstrap/bootstrap.bundle.min.js','bootstrap.bundle.min.js'],['jquery/jquery.min.js','jquery.min.js']])fs.copyFileSync(path.join(libraries,a),path.join(dir,'vendor',b));
 for(const file of ['data.js','app.js'])fs.copyFileSync(path.join(__dirname,file),path.join(dir,file));
 const variables=Object.entries(d.colors).map(([key,value])=>'--'+(key==='onAccent'?'on-accent':key)+':'+value).join(';');
 fs.writeFileSync(path.join(dir,'style.css'),':root{'+variables+'}\n'+fs.readFileSync(path.join(__dirname,'base.css'),'utf8')+'\n'+d.css);
 const num=d.id.match(/portal-(\d+)/)[1];
 fs.writeFileSync(path.join(dir,'index.html'),'<!DOCTYPE html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>[組織名稱]｜資訊服務共用入口 · '+esc(d.name)+'</title><link rel="stylesheet" href="vendor/bootstrap.min.css"><link rel="stylesheet" href="style.css"><script src="vendor/jquery.min.js" defer></script><script src="vendor/bootstrap.bundle.min.js" defer></script><script src="data.js" defer></script><script src="app.js" defer></script></head><body class="design-'+num+'" data-design-name="'+esc(d.name)+'"><a class="skip-link" href="#login-section">跳至登入</a>'+demo+'<div id="portalDesign" class="site-shell">'+d.render(pieces)+'</div>'+result+modal+'</body></html>');
 fs.writeFileSync(path.join(dir,'README.md'),'# '+d.name+'\n\n'+d.description+'\n\n直接開啟 index.html。頂端「展示控制」可切換直接入口／目標系統、服務狀態、登入結果。按「填入示範資料」再送出登入。預設服務狀態為未確認。\n\n此資料夾可獨立離線使用；vendor 包含 Bootstrap 5.3.3 / jQuery 3.7.1。父層總覽連結需要保留父層index.html。data.js 是可替換的公開示範資料；app.js 處理固定情境，不連接驗證或權限API，不傳送或儲存帳號密碼。\n\n可用網址參數 `?target=hr`、`?target=docs`、`?target=supply` 示範來源系統，其他target退回共用入口。前兩者有示範權限，採購沒有示範權限。任意returnUrl不會導向。\n');
}
fs.writeFileSync(path.join(root,'portal-designs.json'),JSON.stringify(designs.map(({render,css,...d})=>d),null,2));
if(!fs.existsSync(path.join(root,'prior-designs.html')))fs.copyFileSync(path.join(root,'index.html'),path.join(root,'prior-designs.html'));
const cards=designs.map((d,i)=>`<article class="gallery-card"><a class="preview-link" href="${d.id}/index.html" aria-label="開啟 ${esc(d.name)}"><div class="preview-frame" style="background:${d.colors.bg}"><img src="${d.id}/desktop-preview.png" alt="${esc(d.name)}桌面預覽" loading="lazy"><span class="card-number">${String(i+1).padStart(2,'0')}</span></div></a><div class="card-copy"><span class="eyebrow">${esc(d.en)}</span><h2><a href="${d.id}/index.html">${esc(d.name)} <span aria-hidden="true">↗</span></a></h2><p>${esc(d.description)}</p><dl><dt>登入配置</dt><dd>${esc(d.loginPosition)}</dd><dt>適用情境</dt><dd>${esc(d.fit)}</dd></dl><div class="card-actions"><a href="${d.id}/index.html">開啟示範</a><a href="${d.id}/index.html?target=hr">目標系統導入 ↗</a></div></div></article>`).join('');
const shell=(title,body)=>'<!DOCTYPE html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><link rel="stylesheet" href="portal-gallery.css"></head><body><main class="gallery-shell"><header class="gallery-header"><a href="index.html">[組織名稱] <span>資訊服務設計提案</span></a><nav><a href="index.html">十款總覽</a><a href="decision.html">比較與選型</a><a href="prior-designs.html">先前設計</a></nav></header>'+body+'<footer class="gallery-footer"><span>Bootstrap 5.3.3 + jQuery 3.7.1 · 資源皆在本機</span><span>前端原型，無真實驗證、權限查詢或服務監測</span></footer></main></body></html>';
fs.writeFileSync(path.join(root,'index.html'),shell('十款多系統共用登入入口',`<section class="gallery-intro"><div><span class="eyebrow">ONE ENTRANCE. CLEAR NEXT STEPS.</span><h1>一個共用入口，<br>清楚的每一步。</h1><p>如何登入、服務是否受影響、遇到問題如何求助。<br>十款使用同一組功能與資料，探索不同的資訊配置。</p><a class="guide-cta" href="decision.html">閱讀比較與選型建議 ↗</a></div><div class="edition-number" aria-hidden="true">10<small>SHARED PORTAL<br>DESIGN EXPLORATIONS</small></div></section><section class="scope-notice"><b>本次是組織共用入口。</b><span>組織品牌與聯絡方式是替換欄位；業務系統與狀態清楚標示為示範。共用畫面不代表完成 SSO。</span></section><div class="gallery-section-line"><span>選擇設計，開啟可操作的完整原型</span><span>桌機 · 平板 · 手機</span></div><section class="gallery-grid">${cards}</section><section class="try-guide"><h2>用同樣的情境，公平比較。</h2><ol><li>開啟一款，按「填入示範資料」並登入，查看示範系統清單。</li><li>展開頂端「展示控制」，改為業務系統導入，觀察目標識別與返回結果。</li><li>切換部分異常或維護中，確認送出前能看見影響與可採取的行動。</li><li>切換驗證失敗、服務無法使用、逾時或無權限，檢查下一步與免登入支援。</li></ol><p>示範資料僅在記憶體中使用，重新整理即可重置；不應輸入真實密碼。</p></section>`));
const rows=designs.map((d,i)=>`<tr><th scope="row"><a href="${d.id}/index.html">${String(i+1).padStart(2,'0')} ${esc(d.name)}</a></th><td>${esc(d.positioning)}</td><td>${esc(d.structure)}<br><b>登入：</b>${esc(d.loginPosition)}</td><td>${esc(d.announcementStyle)}<br><b>導覽：</b>${esc(d.navigation)}</td><td>${esc(d.visualLanguage)}</td><td>${esc(d.fit)}</td><td>${esc(d.tradeoff)}</td></tr>`).join('');
const recommendations=[
['01','首選：晴白服務台','登入與服務訊息並列，常用支援容易找到，元件與頁面結構直觀，適合作為大型組織的共用基準。','正式品牌、長系統名稱與高影響通知需以實際內容測試；限制公告摘要長度。'],
['08','桌機與值班：高效工作站','登入、狀態公告與免登入支援同時可見，適合醫院共用工作站、固定桌機及經常處理異常通報的單位。','三欄需以長聯絡資料與實際公告測試；平板與小螢幕要保持登入優先，避免資訊過密。'],
['05','新進引導：清楚三步','以確認入口、帳號登入、前往系統解釋兩種登入情境，右側協助保持可見，適合新進同仁與多種帳號操作經驗的組織。','步驟是說明導覽，不是額外驗證；正式文案應與實際帳號、權限申請及導向流程一致。']
];
const rec= recommendations.map(([num,title,reason,adjust])=>`<article><span class="eyebrow">RECOMMENDATION / ${num}</span><h3>${title}</h3><p>${reason}</p><p><b>正式前調整：</b>${adjust}</p></article>`).join('');
const questions=[['帳號與驗證','帳號由何單位管理、帳號格式與申請流程？採用既有驗證服務、SSO、AD／LDAP 或其他方式？MFA、帳號同步、密碼到期與帳號限制是否適用？目前均未宣稱支援。'],['系統導向與權限','來源系統如何識別？允許返回哪些網址與路徑，誰維護允許清單？權限由哪個服務提供，何時刷新，如何處理無權限與零系統清單？導向與授權必須由後端再次驗證。'],['服務狀態與公告','誰負責發布及確認？來源為何、多久更新、多久未更新視為未知？公告嚴重度、受影響系統、發布時間、有效期限、可見範圍及替代作法如何核准？登入前API不得回傳敏感內容。'],['支援與服務管理','請提供資訊室分機、郵件、服務時段、值班與非服務時段支援、業務替代流程的負責窗口。報修是否可免登入，摘要提交到哪個服務，需哪些最少資訊？不承諾未確認的處理時限。'],['共用工作站與工作階段','共用與個人設備如何判斷？分別制定記住帳號與保持登入政策、閒置逾時、跨系統登出及重新驗證。電腦名稱與個人歷史紀錄由何處取得、何時可顯示？'],['正式資料與驗收','補齊品牌/Logo、帳號說明、隱私與使用條款。確認瀏覽器支援、內網依賴、無障礙目標、弱網路/逾時、資安審查與稽核紀錄。用真實同仁與輔助科技測試，不以設計評估替代實證。']].map(([h,p])=>`<details><summary>${h}</summary><p>${p}</p></details>`).join('');
fs.writeFileSync(path.join(root,'decision.html'),shell('比較、選型與整合條件｜共用登入入口',`<section class="report-heading"><span class="eyebrow">INFORMATION SERVICE DESIGN REVIEW</span><h1>從使用情境，選擇入口。</h1><p>以下為設計評估，尚未經使用者測試；不宣稱已證實提升效率。</p></section><section class="report-section"><h2>共同資訊架構與流程</h2><div class="principle-grid"><article><h3>01 如何登入</h3><p>組織與共用入口識別、帳號說明、目標系統、表單與帳號協助。直接開啟後選擇示範系統；來源系統導入則示範返回。</p></article><article><h3>02 是否受影響</h3><p>預設狀態未確認。重大異常在登入前顯示影響、時間、處理情形、現在可做、替代方式與最後更新。一般公告只顯示兩則摘要。</p></article><article><h3>03 如何取得協助</h3><p>免登入聯絡、帳號/權限申請說明、常見問題與報修摘要。失敗訊息附下一步，不揭露帳號是否存在。</p></article></div><p class="report-note">主動補充：報修摘要減少反覆問答；非服務時段窗口照顧值班情境；未知狀態避免誤導；共用工作站提醒與驗證後的紀錄界線保護個人資料。</p></section><section class="report-section"><h2>十款差異比較</h2><p>比較同一目錄中新建的十款共用入口；<a href="prior-designs.html">先前單一系統提案</a>保留供歷史參照。</p><div class="comparison-scroll"><table><thead><tr><th>設計</th><th>定位</th><th>版面結構</th><th>公告與導覽</th><th>視覺特色</th><th>適用情境</th><th>主要取捨</th></tr></thead><tbody>${rows}</tbody></table></div></section><section class="report-section"><h2>一致的評估標準</h2><div class="criteria-grid">${[['登入辨識度','入口品牌、帳號與目標是否清楚，表單是否易找。'],['訊息理解度','影響與下一步是否明確，未知與示範是否清楚。'],['求助便利性','失敗後是否能免登入聯絡、查FAQ或產生摘要。'],['無障礙','標籤、文字對比、觸控、鍵盤焦點與動態訊息。'],['跨裝置體驗','手機是否先見登入，求助與重大通知是否可達。'],['維護成本','是否使用共用資料與行為，版型特例是否可控制。']].map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div><p>各款逐項定性評估與假設記錄於 <a href="DECISION-GUIDE.md">完整決策說明</a>；視覺變體共用同一份互動與公開資料模型。</p></section><section class="report-section"><h2>建議優先驗證的三款</h2><div class="recommendation-grid">${rec}</div></section><section class="report-section"><h2>真正影響落地的待確認事項</h2><div class="integration-list">${questions}</div></section><section class="report-section"><h2>資料與範圍界線</h2><p>品牌、Logo、聯絡及服務時段為明確替換欄位；系統、帳密、權限、公告日期與狀態皆為標示的展示資料。公告有效期限以固定示範時點檢核，非真實服務時程。</p><p>不送出或儲存帳號密碼，不建立真實帳號，不執行權限申請或報修送件。登入後僅呈現系統清單、權限說明與導向結果。SSO、AD／LDAP、MFA、同步及正式API均未整合。</p></section>`));
const guide=path.join(__dirname,'DECISION-GUIDE.md');if(fs.existsSync(guide))fs.copyFileSync(guide,path.join(root,'DECISION-GUIDE.md'));
fs.writeFileSync(path.join(root,'README.md'),'# 多系統共用登入入口｜10 款前端原型\n\n開啟 index.html 比較十款；decision.html 包含架構、比較、前三款建議與整合問題。DECISION-GUIDE.md 提供完整設計評估。舊版保留於 prior-designs.html。\n\n'+designs.map(d=>'- `'+d.id+'/index.html` — '+d.name).join('\n')+'\n\n## 操作\n\n頂端「展示控制」可切換直接入口／目標系統，正常／未知／部分異常／維護，以及成功／驗證失敗／網路或登入服務無法使用／工作階段逾時／無權限。先按「填入示範資料」，再示範登入。可直接使用 `?target=hr`、`?target=docs`、`?target=supply`；未識別target退回共用入口，任意返回網址不會執行導向。\n\n預設狀態未確認。只接受demo.user與Demo-only-123，非示範輸入會清除。登入資料不送出、不寫入cookies或Web Storage。問題回報只產生可複製摘要，不送件。\n\n## 資料與整合\n\n每款的data.js是公開示範資料。組織、Logo、聯絡窗口為占位欄位，公告與狀態均為展示；正式前須替換。公告資料包括發布單位、等級、系統、發布與失效時間、公開範圍及各操作指引。固定示範時點用於資料有效期限。\n\n正式驗證、SSO/AD/LDAP/MFA、權限、導向允許清單、公告與狀態來源、服務管理與個人登入紀錄均待整合。不應把前端情境切換當作實際授權控制。\n\n## 開發\n\nportal-src為共用原始碼。從專案根目錄執行`node LoginDemoCode/build.cjs`產生十款；現有Bootstrap5.3.3與jQuery3.7.1從LoginDemoCC本機資源複製。每款是獨立可離線HTML/CSS/JS，無遠端字型、圖片或CDN。verify.cjs驗證共用流程與十款版面；預覽圖與portal-verification.json保留驗證結果。\n');
console.log('Built '+designs.length+' shared portal designs.');

