const { chromium }=require('C:/Users/richs/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');const allDesigns=JSON.parse(fs.readFileSync(path.join(root,'portal-designs.json'),'utf8'));const selected=process.argv.slice(2);const designs=allDesigns.filter(d=>!selected.length||selected.includes(d.id.match(/portal-(\d+)/)[1]));
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[],requests=[],results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
const assert=(condition,message)=>{if(!condition)throw Error(message)};
const open=async d=>{await page.goto(pathToFileURL(path.join(root,d.id,'index.html')).href);await page.waitForFunction(()=>document.querySelector('#targetName').textContent.length>0)};
const controls=async()=>page.locator('#demoControls').evaluate(e=>e.open=true);
const scene=async({target='direct',status='unknown',outcome='success'}={})=>{await controls();await page.locator('#demoTarget').selectOption(target);await page.locator('#demoService').selectOption(status);await page.locator('#demoOutcome').selectOption(outcome)};
const login=async()=>{await page.locator('[data-action="fill-demo"]').click();await page.locator('#loginSubmit').click();assert(await page.locator('#loginSubmit').isDisabled(),'loading / duplicate-submit prevention');await page.waitForFunction(()=>!document.querySelector('#loginSubmit').disabled)};
const modal=async(action)=>{await page.locator('[data-action="'+action+'"]').filter({visible:true}).first().click();await page.locator('#portalModal').waitFor({state:'visible'});await page.waitForFunction(()=>!bootstrap.Modal.getInstance(document.getElementById('portalModal'))._isTransitioning)};
const closeModal=async()=>{await page.locator('.modal-done').click();await page.locator('#portalModal').waitFor({state:'hidden'})};
// Capture every initial design first, so visual review can run alongside flow verification.
for(const d of designs){await page.setViewportSize({width:1440,height:1050});await open(d);
 assert((await page.locator('.status-label').textContent()).includes('未確認'),d.id+' default status');
 const duplicates=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i)});assert(!duplicates.length,d.id+' duplicate IDs '+duplicates);
 for(const selector of ['.org-header','.portal-intro','#login-section','#status-section','#news-section','#support-section','.portal-footer'])assert(await page.locator(selector).count()===1,d.id+' core section '+selector);
 assert(await page.evaluate(()=>jQuery.fn.jquery==='3.7.1'&&bootstrap.Modal.VERSION==='5.3.3'),d.id+' local libraries');
 await page.screenshot({path:path.join(root,d.id,'desktop-preview.png'),fullPage:true});
 for(const [width,height]of [[375,850],[768,1024],[1024,768],[812,375]]){await page.setViewportSize({width,height});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),d.id+' overflow '+width);if(width===375)await page.screenshot({path:path.join(root,d.id,'mobile-preview.png'),fullPage:true})}
 console.log(d.id+' initial layout passed');
}
await page.emulateMedia({reducedMotion:'reduce'});
for(const d of designs){await page.setViewportSize({width:1440,height:1050});await open(d);
 await page.locator('#loginSubmit').click();assert((await page.locator('#accountError').textContent()).includes('請填寫'),'empty account');assert(await page.locator('#account').evaluate(e=>document.activeElement===e),'validation focus');
 await page.locator('[data-action="fill-demo"]').click();await page.locator('#togglePassword').click();assert(await page.locator('#password').getAttribute('type')==='text','show password');await page.locator('#togglePassword').click();assert(await page.locator('#password').getAttribute('type')==='password','hide password');
 await page.locator('#account').fill('not-a-demo');await page.locator('#password').fill('not-a-real-secret');await page.locator('#loginSubmit').click();assert((await page.locator('#feedbackCode').textContent()).includes('DEMO-INPUT'),'non-demo input rejected');assert(await page.locator('#password').inputValue()===''&&await page.locator('#account').inputValue()==='','non-demo cleared');
 await scene();await login();assert(await page.locator('#resultView').isVisible(),'direct result');assert(await page.locator('.system-option').count()===2,'permission-scoped list');assert((await page.locator('#resultHeading').textContent()).includes('選擇系統'),'direct flow title');
 await page.locator('[data-action="destination"]').first().click();assert((await page.locator('#resultHeading').textContent()).includes('導向結果'),'destination receipt');await modal('report');assert((await page.locator('#reportOutput').inputValue()).includes('人事差勤'),'report preserves selected destination');await closeModal();
 await scene({target:'hr'});assert((await page.locator('#targetName').textContent()).includes('人事差勤'),'target context');await login();assert((await page.locator('#resultHeading').textContent()).includes('導向結果'),'target return');
 await scene({target:'supply'});await login();assert((await page.locator('#resultHeading').textContent()).includes('沒有使用權限'),'target denied');await modal('permission');assert((await page.locator('#modalContent').textContent()).includes('採購申請'),'permission help current target');await closeModal();
 await scene({outcome:'credentials'});await login();assert((await page.locator('#feedbackCode').textContent()).includes('DEMO-AUTH'),'credentials failure');assert(!(await page.locator('#feedbackMessage').textContent()).includes('帳號不存在'),'no account enumeration');assert(await page.locator('#password').inputValue()==='','password cleared after failure');
 await scene({outcome:'network'});await login();assert((await page.locator('#feedbackCode').textContent()).includes('DEMO-NET'),'network failure');await modal('report');const report=await page.locator('#reportOutput').inputValue();assert(report.includes('DEMO-NET')&&report.includes('發生時間'),'report context');assert(!report.includes('Demo-only-123'),'report no password');await closeModal();
 await scene({target:'docs',outcome:'timeout'});assert((await page.locator('#feedbackCode').textContent()).includes('DEMO-SESSION'),'timeout on entry');await login();assert((await page.locator('#resultHeading').textContent()).includes('導向結果'),'timeout relogin target preserved');
 await scene({outcome:'denied'});await login();assert((await page.locator('#resultHeading').textContent()).includes('沒有使用權限'),'direct denied scenario');await page.locator('[data-action="system-list"]').click();assert(await page.locator('.system-option').count()===0,'empty permission list');
 for(const [status,affected,unaffected]of [['partial','hr','docs'],['maintenance','docs','hr']]){await scene({target:affected,status});assert(await page.locator('#impactAlert').isVisible(),'prelogin impact '+status);assert(await page.locator('#impactAlert').evaluate(e=>e.getBoundingClientRect().top<document.querySelector('#loginSubmit').getBoundingClientRect().top),'impact before submit');assert((await page.locator('#impactAlternative').textContent()).length>0,'alternative explanation');await login();assert((await page.locator('#resultHeading').textContent()).includes('受影響'),'affected destination paused');await scene({target:unaffected,status});assert(!(await page.locator('#impactAlert').isVisible()),'unaffected target has no blocking alert');await login();assert((await page.locator('#resultHeading').textContent()).includes('導向結果'),'unaffected destination');}
 await scene({status:'normal'});assert((await page.locator('.status-label').textContent()).includes('正常'),'normal explicitly demo');
 await page.locator('#news-section').evaluate(e=>{for(const d of e.closest('details')?[e.closest('details')]:[])d.open=true});
 await page.locator('.notice-open').first().click();await page.locator('#portalModal').waitFor({state:'visible'});await closeModal();
 await page.locator('#support-section').evaluate(e=>{for(let p=e.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true});
 for(const action of ['forgot','account','permission','first','contact','privacy','workstation','integration','all-notices','service-detail']){await modal(action);assert((await page.locator('#modalContent').textContent()).trim().length>0,'help '+action);await closeModal()}
 await page.locator('.faq-list summary').first().click();assert(await page.locator('.faq-list details').first().getAttribute('open')!==null,'FAQ expands');
 const storage=await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length,cookie:document.cookie}));assert(storage.local===0&&storage.session===0&&!storage.cookie,'no auth storage');
 results.push({id:d.id,passed:true});console.log(d.id+' all flows passed');
}
// Query handling is shared, verified once using a copied request context.
const testUrl=pathToFileURL(path.join(root,designs[0].id,'index.html')).href;
await page.goto(testUrl+'?target=hr&returnUrl=https://example.invalid');assert((await page.locator('#targetName').textContent()).includes('人事差勤'),'allowlisted target query');await login();assert(page.url().startsWith('file:'),'no arbitrary return URL navigation');
await page.goto(testUrl+'?target=untrusted');assert(await page.locator('#invalidTarget').isVisible(),'unknown target fallback');
// Public/scenario/expiry filters: add harmless fixtures only to browser memory.
await page.evaluate(()=>{const copy={...PortalData.announcements[2]};PortalData.announcements.push({...copy,id:'fixture-private',visibility:'internal',title:'PRIVATE-FIXTURE'},{...copy,id:'fixture-expired',validUntil:'2020-01-01T00:00:00Z',title:'EXPIRED-FIXTURE'},{...copy,id:'fixture-future',publishedAt:'2040-01-01T00:00:00Z',title:'FUTURE-FIXTURE'});document.querySelector('.notice-filter[data-filter="all"]').click()});assert(!(await page.locator('.news-list').textContent()).includes('FIXTURE'),'public current notices only');
await page.goto(pathToFileURL(path.join(root,'index.html')).href);assert(await page.locator('.gallery-card').count()===10,'ten designs gallery');await page.setViewportSize({width:1440,height:1050});await page.screenshot({path:path.join(root,'portal-overview.png'),fullPage:true});await page.setViewportSize({width:375,height:850});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),'gallery mobile');
await page.goto(pathToFileURL(path.join(root,'decision.html')).href);assert(await page.locator('tbody tr').count()===10,'comparison table');
assert(errors.length===0,'page errors '+errors.join(';'));assert(requests.length===0,'unexpected remote requests '+requests.join(';'));
const reportPath=path.join(root,'portal-verification.json');const prior=selected.length&&fs.existsSync(reportPath)?JSON.parse(fs.readFileSync(reportPath,'utf8')).results:[];const combined=[...prior.filter(r=>!results.some(n=>n.id===r.id)),...results].sort((a,b)=>a.id.localeCompare(b.id));
fs.writeFileSync(reportPath,JSON.stringify({results:combined,lastRegression:designs.map(d=>d.id),pageErrors:errors,remoteRequests:requests,checks:['ten layouts, required sections and IDs','local Bootstrap5.3.3/jQuery3.7.1','375/768/1024/1440, 812x375 landscape','required fields and focus','password visibility and clearing','demo-only input','processing and duplicate prevention','direct system list and allowed return','generic credential failure','network failure and report summary including selected destination','session timeout and relogin','denied and empty permission list','unknown/normal/partial/maintenance','relevant prelogin impact and affected return handling','notice details, public/expiry/future filters','help without login and FAQ','no credential persistence or remote requests','allowlisted target query and no arbitrary redirect','comparison and gallery'],note:'Automated prototype checks; not user testing or a complete accessibility certification.'},null,2));await browser.close();console.log('ALL SHARED PORTAL CHECKS PASSED');})().catch(e=>{console.error(e);process.exit(1)});
