"use strict";
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',book:'<path d="M12 5v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2Z"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.5 2.5 0 0 1 5 0c0 2-2.5 2-2.5 4m0 3h.01"/>',monitor:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/>'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[el.dataset.icon]}</svg>`);
const news=[{scope:'global',tag:'系統維護',date:'2026.09.12',title:'院內系統例行維護通知｜9/19 凌晨暫停服務',pin:true,body:'【示範公告】\n預計維護時間：2026/09/19 02:00–04:00。\n影響範圍：全院系統。請預先儲存作業，實際維護安排以資訊室正式公告為準。'},{scope:'ess',tag:'功能更新',date:'2026.09.10',title:'員工入口 v2.6.0 上線，常用服務更好找',body:'【示範更版內容】\n• 新增常用服務捷徑。\n• 整合全院及員工入口公告分類。\n• 改善行動裝置登入體驗。\n• 新增登入紀錄與裝置資訊呈現。'},{scope:'global',tag:'全院公告',date:'2026.09.08',title:'資訊安全提醒：定期更新密碼，保護您的帳號',body:'【示範公告】\n請勿與他人共用帳號密碼。使用共用電腦後請登出。收到可疑登入通知時，請透過院內通訊錄聯絡資訊室。'},{scope:'ess',tag:'操作教學',date:'2026.09.05',title:'新進同仁看這裡！員工入口快速上手指南',body:'【示範公告】\n1. 確認系統名稱為「員工入口系統 ESS」。\n2. 使用已啟用的院內員工帳號。\n3. 登入後從常用服務進入功能，並確認登入紀錄。\n4. 使用完畢後登出系統。'}];
const dialog=document.getElementById('dialog');function show(title,body){document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-content').textContent=body;dialog.showModal();}
function render(filter='all'){const list=document.getElementById('news');list.replaceChildren();news.filter(n=>filter==='all'||n.scope===filter).forEach(n=>{const b=document.createElement('button');b.className='news-item';b.innerHTML=`<span><span class="news-meta"><span class="badge ${n.pin?'maintenance':''}">${n.tag}</span><span>${n.scope==='global'?'全院系統':'員工入口'}</span><time>${n.date}</time>${n.pin?'<span class="pin">置頂</span>':''}</span><strong>${n.title}</strong></span><span class="chevron" aria-hidden="true">›</span>`;b.addEventListener('click',()=>show(n.title,n.body));list.append(b);});}render();
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});render(b.dataset.filter);}));
const content={guide:['系統功能與使用指南','【原型操作指南】\n1. 確認登入系統為「員工入口系統 ESS」。\n2. 輸入帳號密碼，眼睛按鈕可切換密碼顯示。\n3. 公告可篩選全院系統或員工入口，點選閱讀完整內容。\n4. 個人的登入紀錄需完成身分驗證後查看。\n\n正式系統功能手冊與影片連結待資訊室提供。'],support:['聯絡資訊室','維護單位：振興醫院資訊室\n負責系統：員工入口系統 ESS\n\n聯絡方式：請由院內通訊錄查詢資訊室服务窗口。\n服務分機、電子郵件與服務時間：待維護單位提供。\n\n報修請提供系統名稱 ESS、問題發生時間及錯誤畫面，請勿提供密碼。'],forgot:['忘記密碼／更改密碼','正式環境將由院內帳號服務處理密碼重設與變更。\n\n可透過院內通訊錄聯絡資訊室，依身分驗證流程申請重設。\n\n此原型尚未串接密碼服務，沒有送出重設申請。'],release:['版本資訊 · v2.6.0','【示範版本資料】\n系統：員工入口系統 ESS\n版本：v2.6.0\n更新日期：2026/09/10\n維護單位：資訊室\n\n'+news[1].body],privacy:['資訊安全說明','此頁為登入介面原型，沒有連接帳號驗證服務，也不會儲存或傳送輸入的帳號密碼。\n\n作業系統與瀏覽器依瀏覽器資訊推測。電腦名稱需由院內裝置服務提供；個人的最後登入時間與地點，應在身分驗證完成後由後端提供。'],all:['所有公告（示範）',news.map(n=>n.date+' · '+n.title+'\n'+n.body).join('\n\n')]};
document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>show(...content[b.dataset.modal])));['close','done'].forEach(id=>document.getElementById(id).addEventListener('click',()=>dialog.close()));
const account=document.getElementById('account'),password=document.getElementById('password'),toggle=document.getElementById('toggle');toggle.addEventListener('click',()=>{const visible=password.type==='password';password.type=visible?'text':'password';toggle.setAttribute('aria-label',visible?'隱藏密碼':'顯示密碼');toggle.setAttribute('aria-pressed',String(visible));});
[account,password].forEach(input=>input.addEventListener('input',()=>{input.removeAttribute('aria-invalid');document.getElementById(input.id+'-error').textContent='';document.getElementById('message').textContent='此為互動原型，請勿輸入真實密碼。';}));
document.getElementById('login-form').addEventListener('submit',e=>{e.preventDefault();let first=null;[account,password].forEach(input=>{const valid=Boolean(input===account?input.value.trim():input.value);input.setAttribute('aria-invalid',String(!valid));document.getElementById(input.id+'-error').textContent=valid?'':`請輸入${input===account?'員工帳號':'密碼'}。`;if(!valid&&!first)first=input;});if(first){first.focus();return;}password.value='';password.type='password';toggle.setAttribute('aria-label','顯示密碼');toggle.setAttribute('aria-pressed','false');document.getElementById('message').textContent='欄位檢查完成；尚未串接登入服務，未進行驗證。';});
document.getElementById('today').textContent=new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'long',timeZone:'Asia/Taipei'}).format(new Date());document.getElementById('year').textContent=new Date().getFullYear();const ua=navigator.userAgent;document.getElementById('os').textContent=/iPhone|iPad|iPod/.test(ua)||(/Macintosh/.test(ua)&&navigator.maxTouchPoints>1)?'iOS / iPadOS':/Android/.test(ua)?'Android':/Windows/.test(ua)?'Windows':/Mac/.test(ua)?'macOS':/Linux/.test(ua)?'Linux':'無法辨識';document.getElementById('browser').textContent=(/Edg\//.test(ua)?'Microsoft Edge':/Firefox\//.test(ua)?'Firefox':/Chrome\//.test(ua)?'Google Chrome':/Safari\//.test(ua)?'Safari':'無法辨識瀏覽器')+'（推測）';
