// 2023 ICD-10-CM 疼痛相關子集 ── 每個代碼對應到人體圖細區部位（region_id）
// 資料結構：{ code, name, regions: [region_id...], note? }
// regions 對應 01_人體區域編碼表.md 的細區（L3）或中區（L2）region_id。
// 選到哪個 ICD-10 代碼，就在人體圖上標示對應的可能疼痛部位。
window.ICD10_PAIN_MASTER = [
  /* ═══════════ 頭痛與顏面疼痛（G43–G44, R51） ═══════════ */
  { code: "G43.0", name: "偏頭痛（無先兆）", regions: ["LEFT_TEMPLE", "RIGHT_TEMPLE", "FOREHEAD", "OCCIPUT"] },
  { code: "G43.1", name: "偏頭痛（有先兆）", regions: ["LEFT_TEMPLE", "RIGHT_TEMPLE", "FOREHEAD"] },
  { code: "G43.9", name: "偏頭痛（未明示）", regions: ["LEFT_TEMPLE", "RIGHT_TEMPLE", "FOREHEAD", "OCCIPUT"] },
  { code: "G44.2", name: "緊張型頭痛", regions: ["FOREHEAD", "OCCIPUT", "LEFT_TEMPLE", "RIGHT_TEMPLE", "BACK_NECK"] },
  { code: "G44.3", name: "慢性創傷後頭痛", regions: ["FOREHEAD", "OCCIPUT", "SCALP"] },
  { code: "G44.8", name: "其他特定頭痛症候群", regions: ["FOREHEAD", "OCCIPUT", "LEFT_TEMPLE", "RIGHT_TEMPLE"] },
  { code: "R51", name: "頭痛", regions: ["FOREHEAD", "OCCIPUT", "LEFT_TEMPLE", "RIGHT_TEMPLE", "SCALP"] },
  { code: "G50.0", name: "三叉神經痛", regions: ["LEFT_CHEEK", "RIGHT_CHEEK", "FOREHEAD", "CHIN", "LEFT_EYE", "RIGHT_EYE"] },
  { code: "G50.1", name: "非典型顏面痛", regions: ["FACE", "LEFT_CHEEK", "RIGHT_CHEEK"] },
  { code: "G51.0", name: "貝爾氏麻痺（顏面神經）", regions: ["FACE", "LEFT_CHEEK", "RIGHT_CHEEK"] },

  /* ═══════════ 頸部與肩部（M53, M54, M75） ═══════════ */
  { code: "M53.0", name: "頸顱症候群", regions: ["BACK_NECK", "OCCIPUT", "LEFT_SHOULDER", "RIGHT_SHOULDER"] },
  { code: "M53.1", name: "頸臂症候群", regions: ["BACK_NECK", "LEFT_SHOULDER", "RIGHT_SHOULDER", "LEFT_UPPER_ARM", "RIGHT_UPPER_ARM"] },
  { code: "M54.2", name: "頸痛", regions: ["BACK_NECK", "LEFT_NECK", "RIGHT_NECK"] },
  { code: "M54.3", name: "坐骨神經痛", regions: ["BACK_LOWER", "LEFT_BUTTOCK", "RIGHT_BUTTOCK", "LEFT_THIGH", "RIGHT_THIGH", "LEFT_LOWER_LEG", "RIGHT_LOWER_LEG"] },
  { code: "M54.4", name: "腰痛伴坐骨神經痛", regions: ["BACK_LOWER", "LEFT_BUTTOCK", "RIGHT_BUTTOCK", "LEFT_THIGH", "RIGHT_THIGH"] },
  { code: "M54.5", name: "下背痛", regions: ["BACK_LOWER", "SACRUM", "LEFT_LOWER_BACK", "RIGHT_LOWER_BACK"] },
  { code: "M54.6", name: "胸椎痛", regions: ["BACK_MID", "SPINE", "LEFT_MID_BACK", "RIGHT_MID_BACK"] },
  { code: "M54.8", name: "其他背痛", regions: ["BACK_UPPER", "BACK_MID", "BACK_LOWER", "SPINE"] },
  { code: "M54.9", name: "背痛（未明示）", regions: ["BACK_UPPER", "BACK_MID", "BACK_LOWER", "SPINE"] },
  { code: "M75.0", name: "肩關節沾黏性囊炎（五十肩）", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER"] },
  { code: "M75.1", name: "旋轉肌袖症候群", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER"] },
  { code: "M75.2", name: "二頭肌腱炎", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER", "LEFT_UPPER_ARM", "RIGHT_UPPER_ARM"] },
  { code: "M75.3", name: "肩峰下滑囊炎", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER"] },
  { code: "M75.4", name: "肩關節撞擊症候群", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER"] },
  { code: "M75.5", name: "肩旋轉肌袖撕裂", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER"] },

  /* ═══════════ 上肢（M19, M20, M65, M66, M67, M70, M77） ═══════════ */
  { code: "M19.0", name: "原發性關節病（多處）", regions: ["LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_WRIST", "RIGHT_WRIST", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M19.2", name: "繼發性關節病（肘）", regions: ["LEFT_ELBOW", "RIGHT_ELBOW"] },
  { code: "M19.9", name: "關節病（未明示）", regions: ["LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_WRIST", "RIGHT_WRIST", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M20.1", name: "拇趾外翻（姆趾囊腫）", regions: ["LEFT_BIG_TOE", "RIGHT_BIG_TOE"] },
  { code: "M65.4", name: "橈骨莖突腱鞘炎（狄奎凡氏症）", regions: ["LEFT_WRIST", "RIGHT_WRIST", "LEFT_THUMB", "RIGHT_THUMB"] },
  { code: "M65.9", name: "滑膜炎與腱鞘炎（未明示）", regions: ["LEFT_WRIST", "RIGHT_WRIST", "LEFT_ANKLE", "RIGHT_ANKLE"] },
  { code: "M66.0", name: "肩袖肌腱斷裂", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER"] },
  { code: "M67.4", name: "腱鞘囊腫（腱鞘囊腫）", regions: ["LEFT_WRIST", "RIGHT_WRIST", "LEFT_HAND", "RIGHT_HAND"] },
  { code: "M70.2", name: "鷹嘴滑囊炎（肘）", regions: ["LEFT_ELBOW", "RIGHT_ELBOW"] },
  { code: "M70.3", name: "其他肘滑囊炎", regions: ["LEFT_ELBOW", "RIGHT_ELBOW"] },
  { code: "M77.0", name: "內上髁炎（高爾夫球肘）", regions: ["LEFT_ELBOW", "RIGHT_ELBOW"] },
  { code: "M77.1", name: "外上髁炎（網球肘）", regions: ["LEFT_ELBOW", "RIGHT_ELBOW"] },
  { code: "M77.2", name: "腕部腱鞘炎", regions: ["LEFT_WRIST", "RIGHT_WRIST"] },
  { code: "M77.3", name: "跟骨骨刺", regions: ["LEFT_HEEL", "RIGHT_HEEL"] },
  { code: "M77.4", name: "足中段痛（跗骨痛）", regions: ["LEFT_INSTEP", "RIGHT_INSTEP", "LEFT_SOLE", "RIGHT_SOLE"] },
  { code: "M77.5", name: "足部其他部位病變", regions: ["LEFT_FOOT", "RIGHT_FOOT"] },
  { code: "M77.9", name: "肌腱病變（未明示）", regions: ["LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_WRIST", "RIGHT_WRIST", "LEFT_ANKLE", "RIGHT_ANKLE"] },

  /* ═══════════ 下肢與髖（M16, M17, M23, M25, M76） ═══════════ */
  { code: "M16.0", name: "原發性髖關節病（雙側）", regions: ["LEFT_HIP", "RIGHT_HIP"] },
  { code: "M16.1", name: "原發性髖關節病（單側）", regions: ["LEFT_HIP", "RIGHT_HIP"] },
  { code: "M16.9", name: "髖關節病（未明示）", regions: ["LEFT_HIP", "RIGHT_HIP"] },
  { code: "M17.0", name: "原發性膝關節病（雙側）", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M17.1", name: "原發性膝關節病（單側）", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M17.9", name: "膝關節病（未明示）", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M23.0", name: "膝半月板囊腫", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M23.2", name: "膝半月板病變（舊撕裂）", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M23.4", name: "膝關節游離體", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M23.5", name: "膝慢性不穩定", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M25.5", name: "關節痛（多處）", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_WRIST", "RIGHT_WRIST", "LEFT_ANKLE", "RIGHT_ANKLE"] },
  { code: "M25.6", name: "關節僵硬（多處）", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_SHOULDER", "RIGHT_SHOULDER"] },
  { code: "M76.0", name: "臀肌腱炎", regions: ["LEFT_HIP", "RIGHT_HIP", "LEFT_BUTTOCK", "RIGHT_BUTTOCK"] },
  { code: "M76.1", name: "髂脛束症候群", regions: ["LEFT_HIP", "RIGHT_HIP", "LEFT_THIGH", "RIGHT_THIGH", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M76.3", name: "髂脛束摩擦症候群", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_THIGH", "RIGHT_THIGH"] },
  { code: "M76.4", name: "脛骨內側滑囊炎（鵝足）", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_SHIN", "RIGHT_SHIN"] },
  { code: "M76.5", name: "髕骨肌腱炎（跳躍膝）", regions: ["LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M76.6", name: "跟腱炎", regions: ["LEFT_HEEL", "RIGHT_HEEL", "LEFT_ANKLE", "RIGHT_ANKLE"] },
  { code: "M76.7", name: "腓骨肌腱炎", regions: ["LEFT_ANKLE", "RIGHT_ANKLE", "LEFT_CALF", "RIGHT_CALF"] },
  { code: "M76.8", name: "其他下肢肌腱病變", regions: ["LEFT_THIGH", "RIGHT_THIGH", "LEFT_LOWER_LEG", "RIGHT_LOWER_LEG"] },
  { code: "M76.9", name: "下肢肌腱病變（未明示）", regions: ["LEFT_THIGH", "RIGHT_THIGH", "LEFT_LOWER_LEG", "RIGHT_LOWER_LEG"] },

  /* ═══════════ 神經病變與神經痛（G56, G57, G58, G60, G62） ═══════════ */
  { code: "G56.0", name: "腕隧道症候群", regions: ["LEFT_WRIST", "RIGHT_WRIST", "LEFT_PALM", "RIGHT_PALM", "LEFT_INDEX_FINGER", "RIGHT_INDEX_FINGER", "LEFT_MIDDLE_FINGER", "RIGHT_MIDDLE_FINGER"] },
  { code: "G56.1", name: "正中神經其他病變", regions: ["LEFT_FOREARM", "RIGHT_FOREARM", "LEFT_PALM", "RIGHT_PALM"] },
  { code: "G56.2", name: "尺神經病變", regions: ["LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_FOREARM", "RIGHT_FOREARM", "LEFT_RING_FINGER", "RIGHT_RING_FINGER", "LEFT_LITTLE_FINGER", "RIGHT_LITTLE_FINGER"] },
  { code: "G56.3", name: "橈神經病變", regions: ["LEFT_UPPER_ARM", "RIGHT_UPPER_ARM", "LEFT_FOREARM", "RIGHT_FOREARM", "LEFT_BACK_HAND", "RIGHT_BACK_HAND"] },
  { code: "G56.4", name: "腕部灼痛（複雜性區域疼痛）", regions: ["LEFT_WRIST", "RIGHT_WRIST", "LEFT_HAND", "RIGHT_HAND"] },
  { code: "G56.8", name: "上肢其他單神經病變", regions: ["LEFT_ARM", "RIGHT_ARM"] },
  { code: "G56.9", name: "上肢單神經病變（未明示）", regions: ["LEFT_ARM", "RIGHT_ARM"] },
  { code: "G57.0", name: "坐骨神經病變", regions: ["LEFT_BUTTOCK", "RIGHT_BUTTOCK", "LEFT_THIGH", "RIGHT_THIGH", "LEFT_LOWER_LEG", "RIGHT_LOWER_LEG"] },
  { code: "G57.1", name: "股神經病變", regions: ["LEFT_THIGH", "RIGHT_THIGH", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "G57.2", name: "股外側皮神經病變（感覺異常性股痛）", regions: ["LEFT_THIGH", "RIGHT_THIGH"] },
  { code: "G57.3", name: "腓神經病變", regions: ["LEFT_LOWER_LEG", "RIGHT_LOWER_LEG", "LEFT_INSTEP", "RIGHT_INSTEP", "LEFT_TOES", "RIGHT_TOES"] },
  { code: "G57.4", name: "脛神經病變", regions: ["LEFT_CALF", "RIGHT_CALF", "LEFT_SOLE", "RIGHT_SOLE"] },
  { code: "G57.5", name: "跗隧道症候群", regions: ["LEFT_ANKLE", "RIGHT_ANKLE", "LEFT_SOLE", "RIGHT_SOLE"] },
  { code: "G57.6", name: "足底神經病變", regions: ["LEFT_SOLE", "RIGHT_SOLE", "LEFT_HEEL", "RIGHT_HEEL"] },
  { code: "G57.9", name: "下肢單神經病變（未明示）", regions: ["LEFT_LEG", "RIGHT_LEG"] },
  { code: "G58.0", name: "肋間神經病變", regions: ["LEFT_RIB", "RIGHT_RIB", "LEFT_CHEST", "RIGHT_CHEST"] },
  { code: "G58.8", name: "其他特定單神經病變", regions: ["LEFT_ARM", "RIGHT_ARM", "LEFT_LEG", "RIGHT_LEG"] },
  { code: "G58.9", name: "單神經病變（未明示）", regions: ["LEFT_ARM", "RIGHT_ARM", "LEFT_LEG", "RIGHT_LEG"] },
  { code: "G60.0", name: "遺傳性運動感覺神經病變", regions: ["LEFT_FOOT", "RIGHT_FOOT", "LEFT_HAND", "RIGHT_HAND"] },
  { code: "G62.0", name: "藥物誘發多發性神經病變", regions: ["LEFT_FOOT", "RIGHT_FOOT", "LEFT_HAND", "RIGHT_HAND"] },
  { code: "G62.9", name: "多發性神經病變（未明示）", regions: ["LEFT_FOOT", "RIGHT_FOOT", "LEFT_HAND", "RIGHT_HAND"] },

  /* ═══════════ 胸部與心臟（R07, I20, I21, I26, I48） ═══════════ */
  { code: "R07.1", name: "胸痛（呼吸時）", regions: ["LEFT_CHEST", "RIGHT_CHEST", "LEFT_RIB", "RIGHT_RIB"] },
  { code: "R07.2", name: "心前區痛", regions: ["LEFT_CHEST", "STERNUM", "UPPER_CHEST"] },
  { code: "R07.3", name: "其他胸痛", regions: ["CHEST", "STERNUM", "LEFT_CHEST", "RIGHT_CHEST"] },
  { code: "R07.4", name: "胸痛（未明示）", regions: ["CHEST", "STERNUM", "LEFT_CHEST", "RIGHT_CHEST"] },
  { code: "R07.8", name: "其他胸痛", regions: ["CHEST", "LEFT_RIB", "RIGHT_RIB"] },
  { code: "R07.9", name: "胸痛（未明示）", regions: ["CHEST", "STERNUM"] },
  { code: "I20.0", name: "不穩定型心絞痛", regions: ["LEFT_CHEST", "STERNUM", "LEFT_UPPER_ARM", "LEFT_SHOULDER"] },
  { code: "I20.1", name: "穩定型心絞痛", regions: ["LEFT_CHEST", "STERNUM", "LEFT_UPPER_ARM", "LEFT_SHOULDER"] },
  { code: "I20.8", name: "其他心絞痛", regions: ["LEFT_CHEST", "STERNUM"] },
  { code: "I20.9", name: "心絞痛（未明示）", regions: ["LEFT_CHEST", "STERNUM"] },
  { code: "I21.9", name: "急性心肌梗塞（未明示）", regions: ["LEFT_CHEST", "STERNUM", "LEFT_UPPER_ARM", "LEFT_SHOULDER", "LEFT_LOWER_ABDOMEN"] },
  { code: "I26.9", name: "肺栓塞（無急性肺心症）", regions: ["LEFT_CHEST", "RIGHT_CHEST", "LEFT_RIB", "RIGHT_RIB"] },
  { code: "I48.9", name: "心房顫動（未明示）", regions: ["LEFT_CHEST", "STERNUM"] },

  /* ═══════════ 腹部與消化（R10, K25, K26, K27, K29, K35, K57, K80, K85） ═══════════ */
  { code: "R10.0", name: "急性腹痛", regions: ["UPPER_ABDOMEN", "MID_ABDOMEN", "LOWER_ABDOMEN"] },
  { code: "R10.1", name: "上腹痛", regions: ["UPPER_ABDOMEN", "LEFT_UPPER_ABDOMEN", "RIGHT_UPPER_ABDOMEN"] },
  { code: "R10.2", name: "骨盆腔與會陰痛", regions: ["LOWER_ABDOMEN", "PUBIC_AREA", "GROIN"] },
  { code: "R10.3", name: "臍周痛", regions: ["MID_ABDOMEN", "NAVEL"] },
  { code: "R10.4", name: "其他與未明示腹痛", regions: ["ABDOMEN", "UPPER_ABDOMEN", "MID_ABDOMEN", "LOWER_ABDOMEN"] },
  { code: "R10.8", name: "其他腹部與骨盆腔痛", regions: ["ABDOMEN", "PELVIS"] },
  { code: "R10.9", name: "腹部與骨盆腔痛（未明示）", regions: ["ABDOMEN", "PELVIS"] },
  { code: "K25.9", name: "胃潰瘍（無出血穿孔）", regions: ["UPPER_ABDOMEN", "LEFT_UPPER_ABDOMEN"] },
  { code: "K26.9", name: "十二指腸潰瘍（無出血穿孔）", regions: ["UPPER_ABDOMEN", "RIGHT_UPPER_ABDOMEN"] },
  { code: "K27.9", name: "消化性潰瘍（部位未明示）", regions: ["UPPER_ABDOMEN", "MID_ABDOMEN"] },
  { code: "K29.5", name: "慢性胃炎（未明示）", regions: ["UPPER_ABDOMEN", "LEFT_UPPER_ABDOMEN"] },
  { code: "K29.7", name: "胃炎（未明示）", regions: ["UPPER_ABDOMEN"] },
  { code: "K35.8", name: "急性闌尾炎（其他）", regions: ["RIGHT_LOWER_ABDOMEN", "LOWER_ABDOMEN"] },
  { code: "K35.9", name: "急性闌尾炎（未明示）", regions: ["RIGHT_LOWER_ABDOMEN", "LOWER_ABDOMEN"] },
  { code: "K57.3", name: "憩室炎（大腸）", regions: ["LEFT_LOWER_ABDOMEN", "LOWER_ABDOMEN"] },
  { code: "K57.9", name: "憩室病（大腸，無穿孔膿瘍）", regions: ["LEFT_LOWER_ABDOMEN", "LOWER_ABDOMEN"] },
  { code: "K80.0", name: "膽囊結石伴急性膽囊炎", regions: ["RIGHT_UPPER_ABDOMEN", "UPPER_ABDOMEN"] },
  { code: "K80.1", name: "膽囊結石伴其他膽囊炎", regions: ["RIGHT_UPPER_ABDOMEN", "UPPER_ABDOMEN"] },
  { code: "K80.2", name: "膽囊結石（無膽囊炎）", regions: ["RIGHT_UPPER_ABDOMEN"] },
  { code: "K80.5", name: "膽管結石（無膽管炎膽囊炎）", regions: ["RIGHT_UPPER_ABDOMEN", "UPPER_ABDOMEN"] },
  { code: "K85.0", name: "特發性急性胰臟炎", regions: ["UPPER_ABDOMEN", "LEFT_UPPER_ABDOMEN", "MID_ABDOMEN"] },
  { code: "K85.9", name: "急性胰臟炎（未明示）", regions: ["UPPER_ABDOMEN", "MID_ABDOMEN"] },
  { code: "K86.1", name: "其他慢性胰臟炎", regions: ["UPPER_ABDOMEN", "LEFT_UPPER_ABDOMEN"] },

  /* ═══════════ 泌尿與生殖（N23, N30, N39, N45, N73, N94） ═══════════ */
  { code: "N23", name: "腎絞痛（未明示）", regions: ["BACK_LOWER", "LEFT_LOWER_BACK", "RIGHT_LOWER_BACK", "LEFT_LOWER_ABDOMEN", "RIGHT_LOWER_ABDOMEN"] },
  { code: "N30.0", name: "急性膀胱炎", regions: ["LOWER_ABDOMEN", "PUBIC_AREA"] },
  { code: "N30.9", name: "膀胱炎（未明示）", regions: ["LOWER_ABDOMEN", "PUBIC_AREA"] },
  { code: "N39.0", name: "泌尿道感染（部位未明示）", regions: ["LOWER_ABDOMEN", "PUBIC_AREA"] },
  { code: "N45.0", name: "睪丸炎與副睪炎", regions: ["GROIN", "PUBIC_AREA"] },
  { code: "N45.9", name: "睪丸炎與副睪炎（未明示）", regions: ["GROIN", "PUBIC_AREA"] },
  { code: "N73.9", name: "女性骨盆腔發炎疾病（未明示）", regions: ["LOWER_ABDOMEN", "PUBIC_AREA", "GROIN"] },
  { code: "N94.6", name: "經痛（痛經）", regions: ["LOWER_ABDOMEN", "PUBIC_AREA", "BACK_LOWER"] },
  { code: "N94.8", name: "其他與未明示與月經週期相關狀況", regions: ["LOWER_ABDOMEN", "PUBIC_AREA"] },

  /* ═══════════ 骨骼與關節（M00, M05, M06, M10, M13, M15, M47, M48, M79） ═══════════ */
  { code: "M00.9", name: "化膿性關節炎（未明示）", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_WRIST", "RIGHT_WRIST"] },
  { code: "M05.9", name: "類風濕性關節炎（未明示）", regions: ["LEFT_WRIST", "RIGHT_WRIST", "LEFT_HAND", "RIGHT_HAND", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M06.9", name: "類風濕性關節炎（未明示）", regions: ["LEFT_WRIST", "RIGHT_WRIST", "LEFT_HAND", "RIGHT_HAND", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M10.0", name: "特發性痛風", regions: ["LEFT_BIG_TOE", "RIGHT_BIG_TOE", "LEFT_ANKLE", "RIGHT_ANKLE", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M10.9", name: "痛風（未明示）", regions: ["LEFT_BIG_TOE", "RIGHT_BIG_TOE", "LEFT_ANKLE", "RIGHT_ANKLE", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M13.0", name: "多關節炎（未明示）", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_WRIST", "RIGHT_WRIST"] },
  { code: "M13.9", name: "關節炎（未明示）", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_ELBOW", "RIGHT_ELBOW", "LEFT_WRIST", "RIGHT_WRIST"] },
  { code: "M15.0", name: "原發性全身性骨關節炎", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_HIP", "RIGHT_HIP", "LEFT_HAND", "RIGHT_HAND"] },
  { code: "M15.9", name: "多發性關節病（未明示）", regions: ["LEFT_KNEE", "RIGHT_KNEE", "LEFT_HIP", "RIGHT_HIP"] },
  { code: "M47.8", name: "其他脊椎關節病", regions: ["SPINE", "BACK_NECK", "BACK_MID", "BACK_LOWER"] },
  { code: "M47.9", name: "脊椎關節病（未明示）", regions: ["SPINE", "BACK_NECK", "BACK_MID", "BACK_LOWER"] },
  { code: "M48.0", name: "脊椎管狹窄", regions: ["SPINE", "BACK_LOWER", "BACK_NECK"] },
  { code: "M48.1", name: "強直性脊椎增生（福雷斯蒂爾病）", regions: ["SPINE", "BACK_UPPER", "BACK_MID", "BACK_LOWER"] },
  { code: "M48.2", name: "脊椎接合（未明示）", regions: ["SPINE", "BACK_MID", "BACK_LOWER"] },
  { code: "M79.0", name: "風濕病（未明示）", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER", "LEFT_KNEE", "RIGHT_KNEE", "LEFT_HIP", "RIGHT_HIP"] },
  { code: "M79.1", name: "肌痛", regions: ["LEFT_UPPER_ARM", "RIGHT_UPPER_ARM", "LEFT_THIGH", "RIGHT_THIGH", "LEFT_CALF", "RIGHT_CALF"] },
  { code: "M79.2", name: "神經痛與神經炎（未明示）", regions: ["LEFT_ARM", "RIGHT_ARM", "LEFT_LEG", "RIGHT_LEG"] },
  { code: "M79.6", name: "肢端痛", regions: ["LEFT_HAND", "RIGHT_HAND", "LEFT_FOOT", "RIGHT_FOOT"] },
  { code: "M79.7", name: "纖維肌痛", regions: ["LEFT_SHOULDER", "RIGHT_SHOULDER", "BACK_UPPER", "BACK_LOWER", "LEFT_HIP", "RIGHT_HIP", "LEFT_KNEE", "RIGHT_KNEE"] },
  { code: "M79.8", name: "其他特定軟組織疾病", regions: ["LEFT_THIGH", "RIGHT_THIGH", "LEFT_LOWER_LEG", "RIGHT_LOWER_LEG"] },
  { code: "M79.9", name: "軟組織疾病（未明示）", regions: ["LEFT_ARM", "RIGHT_ARM", "LEFT_LEG", "RIGHT_LEG"] },

  /* ═══════════ 其他疼痛（R52, R10.8, R07.0, R51） ═══════════ */
  { code: "R52", name: "疼痛（未明示）", regions: ["BODY_ALL"] },
  { code: "R52.0", name: "急性疼痛", regions: ["BODY_ALL"] },
  { code: "R52.1", name: "慢性頑固性疼痛", regions: ["BODY_ALL"] },
  { code: "R52.2", name: "其他慢性疼痛", regions: ["BODY_ALL"] },
  { code: "R07.0", name: "喉嚨痛", regions: ["THROAT", "FRONT_NECK"] },
  { code: "R07.8", name: "其他胸痛", regions: ["CHEST", "LEFT_RIB", "RIGHT_RIB"] },
  { code: "R10.8", name: "其他腹部與骨盆腔痛", regions: ["ABDOMEN", "PELVIS"] },
  { code: "R51", name: "頭痛", regions: ["FOREHEAD", "OCCIPUT", "LEFT_TEMPLE", "RIGHT_TEMPLE", "SCALP"] },
  { code: "R52.9", name: "疼痛（未明示）", regions: ["BODY_ALL"] },
];
