const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const configs = [...require('./concepts-01-03.cjs'), ...require('./concepts-04-06.cjs'), ...require('./concepts-07-10.cjs')];
const icons = { grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.5 2.5 0 0 1 5 0c0 2-2.5 2-2.5 4m0 3h.01"/>',monitor:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/>' };
const icon = name => '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">' + icons[name] + '</svg>';
const val = (key, value) => '<span data-value="' + key + '">' + value + '</span>';
const p = {
 header:'<header class="site-header"><a class="hospital-brand" href="../index.html" aria-label="振興醫院，回到設計總覽"><span class="hospital-symbol" aria-hidden="true">+</span><span><strong data-value="org">振興醫院</strong><small>CHENG HSIN GENERAL HOSPITAL</small></span></a><nav class="header-links" aria-label="輔助連結"><a class="desktop-link" href="#serviceModal" data-content="guide">使用指南</a><a href="#serviceModal" data-content="support">聯絡資訊室 ↗</a><span class="concept-tag">LOGIN / DESIGN EXPLORATION</span></nav></header>',
 identity:'<section class="identity" aria-labelledby="systemTitle"><div class="identity-meta"><span class="system-code" data-value="code">CHGH-ESS</span><span class="environment-badge" data-value="environment">展示環境</span></div><h1 id="systemTitle">'+val('name','員工入口系統')+'<span class="system-short" data-value="short">ESS</span></h1><p data-value="tagline">連結院內資源，讓每一天的照護更專注。</p><div class="identity-date"><span class="eyebrow">EMPLOYEE SELF-SERVICE PORTAL</span><time id="currentDate"></time></div></section>',
 login:'<section class="panel login-panel" aria-labelledby="loginHeading"><div class="panel-heading"><div><span class="eyebrow">SIGN IN TO YOUR WORKSPACE</span><h2 id="loginHeading">登入'+val('name','員工入口系統')+'</h2></div><span class="panel-number">'+icon('grid')+'</span></div><div class="login-ident"><span>系統代碼 <b data-value="code">CHGH-ESS</b></span><span data-value="environment">展示環境</span></div><p class="login-intro">歡迎回來，請使用您的院內帳號。</p><form id="loginForm" novalidate><div class="field-block"><label class="form-label" for="account">員工帳號</label><input class="form-control" id="account" name="username" autocomplete="username" spellcheck="false" placeholder="請輸入員工編號或帳號" required aria-describedby="accountError"><div class="field-error" id="accountError" aria-live="polite"></div></div><div class="field-block"><label class="form-label" for="password">密碼</label><div class="password-wrap"><input class="form-control" id="password" name="password" type="password" autocomplete="current-password" placeholder="請輸入密碼" required aria-describedby="passwordError"><button class="password-toggle" id="togglePassword" type="button" aria-label="顯示密碼" aria-pressed="false">'+icon('eye')+'</button></div><div class="field-error" id="passwordError" aria-live="polite"></div></div><div class="password-links"><a href="#serviceModal" data-content="forgot">忘記密碼？</a><a href="#serviceModal" data-content="change">更改密碼 ↗</a></div><button id="loginSubmit" class="btn login-submit" type="submit"><span id="loginButtonText">登入員工入口系統</span>'+icon('arrow')+'</button><p class="login-status" id="loginStatus" role="status">介面展示，不會傳送帳號密碼。</p></form><div class="security-note">'+icon('shield')+'<span>共用電腦使用完畢後，請記得登出系統。</span></div></section>',
 news:'<section class="panel announcement-panel" aria-labelledby="newsHeading"><div class="panel-heading"><div><span class="eyebrow">LATEST UPDATES</span><h2 id="newsHeading">最新公告 <span class="sample-tag">示範資料</span></h2></div><span class="panel-number">'+icon('bell')+'</span></div><div class="news-filters nav nav-pills" role="group" aria-label="篩選公告範圍"><button class="filter-button btn active" data-filter="ALL" aria-pressed="true">全部公告</button><button class="filter-button btn" data-filter="GLOBAL" aria-pressed="false">全系統</button><button class="filter-button btn" data-filter="SYSTEM" aria-pressed="false">本系統 <span data-value="short">ESS</span></button></div><div id="newsList" aria-live="polite"></div><div class="news-bottom"><span id="newsCount"></span><a class="text-action" href="#serviceModal" data-content="all">查看全部公告 ↗</a></div></section>',
 release:'<section class="panel release-panel" aria-labelledby="releaseHeading"><div class="panel-heading"><div><span class="eyebrow">WHAT’S NEW</span><h2 id="releaseHeading">更版資訊</h2></div><span class="sample-tag">示範資料</span></div><div class="version-line"><span class="version-pill" data-value="version">v2.6.0</span><time data-value="releaseDate">2026.09.10</time></div><ul id="releaseChanges" class="release-changes"></ul><a class="text-action" href="#serviceModal" data-content="release">完整更版內容 '+icon('arrow')+'</a></section>',
 support:'<section class="panel support-panel" aria-labelledby="supportHeading"><div class="panel-heading"><div><span class="eyebrow">WE’RE HERE TO HELP</span><h2 id="supportHeading">維護與使用協助</h2></div><span class="panel-number">'+icon('help')+'</span></div><dl class="contact-grid"><dt>維護單位</dt><dd data-value="maintainer">資訊室</dd><dt>聯絡窗口</dt><dd data-value="contact">待維護單位提供</dd><dt>電話／分機</dt><dd id="phoneValue" data-value="phone">待提供，請查詢院內通訊錄</dd><dt>電子郵件</dt><dd id="emailValue" data-value="email">待維護單位提供</dd></dl><div class="support-links"><a class="text-action" href="#serviceModal" data-content="guide">快速上手 ↗</a><a class="text-action" href="#serviceModal" data-content="manual">功能教學與說明 ↗</a></div><a class="text-action" href="#serviceModal" data-content="support">聯絡維護者 '+icon('arrow')+'</a></section>',
 device:'<section class="panel device-panel" aria-labelledby="deviceHeading"><div class="panel-heading"><h2 id="deviceHeading">'+icon('monitor')+' 本次裝置與登入紀錄</h2><a class="text-action" href="#serviceModal" data-content="device">資料來源說明 ↗</a></div><div class="device-grid"><div class="device-item"><span class="device-label">登入電腦名稱</span><strong class="device-value" data-value="computer">尚未取得</strong><small class="device-hint" id="computerHint">待院內裝置服務提供</small></div><div class="device-item"><span class="device-label">作業系統／瀏覽器</span><strong class="device-value" id="clientOs">偵測中</strong><small class="device-hint" id="clientBrowser"></small></div><div class="device-item"><span class="device-label">最後一次登入時間</span><strong class="device-value" data-value="lastTime">登入後可查看</strong><small class="device-hint">驗證後提供個人登入紀錄</small></div><div class="device-item"><span class="device-label">最後一次登入地點</span><strong class="device-value" data-value="lastPlace">登入後可查看</strong><small class="device-hint" data-value="lastComputer">驗證後提供前次使用電腦</small></div></div></section>',
 footer:'<footer class="site-footer"><span>© <span id="currentYear"></span> '+val('org','振興醫院')+' · '+val('name','員工入口系統')+' <b data-value="code">CHGH-ESS</b> · <span data-value="version">v2.6.0</span></span><div class="footer-links"><span>維護：'+val('maintainer','資訊室')+'</span><a href="#serviceModal" data-content="privacy">資訊安全說明</a><a href="../index.html">10 款設計總覽 ↗</a></div></footer>'
};
const modal = '<div class="modal fade" id="serviceModal" tabindex="-1" aria-labelledby="serviceTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title" id="serviceTitle"></h2><button type="button" class="modal-close" data-bs-dismiss="modal" aria-label="關閉視窗">×</button></div><div class="modal-body" id="serviceBody"></div><div class="modal-footer"><button class="modal-done" type="button" data-bs-dismiss="modal">我知道了</button></div></div></div></div>';
const vendors = [ ['bootstrap/bootstrap.min.css','bootstrap.min.css'], ['bootstrap/bootstrap.bundle.min.js','bootstrap.bundle.min.js'], ['jquery/jquery.min.js','jquery.min.js'] ];
const vendorSource = path.resolve(root,'../LoginDemoCC/assets/libs');
for (const c of configs) {
  const dir = path.join(root, c.id); fs.mkdirSync(path.join(dir,'vendor'),{recursive:true});
  for (const [src,target] of vendors) fs.copyFileSync(path.join(vendorSource,src),path.join(dir,'vendor',target));
  for (const file of ['config.js','app.js']) fs.copyFileSync(path.join(__dirname,file),path.join(dir,file));
  const variables = Object.entries(c.colors).map(([k,v]) => '--'+(k==='onAccent'?'on-accent':k)+':'+v).join(';');
  fs.writeFileSync(path.join(dir,'style.css'),':root{'+variables+'}\n'+fs.readFileSync(path.join(__dirname,'base.css'),'utf8')+'\n'+c.css);
  fs.writeFileSync(path.join(dir,'index.html'),'<!DOCTYPE html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>員工入口系統 [CHGH-ESS]｜'+c.name+'</title><link rel="stylesheet" href="vendor/bootstrap.min.css"><link rel="stylesheet" href="style.css"><script src="vendor/jquery.min.js" defer></script><script src="vendor/bootstrap.bundle.min.js" defer></script><script src="config.js" defer></script><script src="app.js" defer></script></head><body class="concept-'+c.id.slice(0,2)+'" data-concept="'+c.name+'"><a class="skip-link" href="#account">跳至登入表單</a><div class="site-shell">'+c.render(p)+'</div>'+modal+'</body></html>');
  fs.writeFileSync(path.join(dir,'README.md'),'# '+c.name+' / '+c.en+'\n\n'+c.description+'\n\n直接開啟 `index.html`。本資料夾包含 Bootstrap 5.3.3、jQuery 3.7.1 與全部樣式/互動，可独立離線開啟。`config.js` 可設定系統名稱、代碼、環境、版本、公告、維護者、正式協助連結與裝置資訊。父層總覽連結需要保留父層檔案。\n\n目前為前端原型，不送出或儲存帳號密碼，無正式驗證。尚未取得的電腦名稱、前次登入紀錄與聯絡資料清楚標示，正式資料須由後端提供。\n');
}
fs.writeFileSync(path.join(root,'concepts.json'), JSON.stringify(configs.map(({id,name,en,description,colors})=>({id,name,en,description,colors})),null,2));
const cards = configs.map((c,i)=>'<a class="concept-card" href="'+c.id+'/index.html" style="--card-accent:'+c.colors.accent+';--card-bg:'+c.colors.bg+'"><div class="preview-frame"><img src="'+c.id+'/desktop-preview.png" alt="'+c.name+'的完整登入頁預覽" loading="lazy"><span class="preview-index">'+String(i+1).padStart(2,'0')+'</span></div><div class="concept-info"><span class="concept-en">'+c.en+'</span><div class="concept-title"><h2>'+c.name+'</h2><span aria-hidden="true">↗</span></div><p>'+c.description+'</p><div class="swatches" aria-label="設計配色">'+[c.colors.bg,c.colors.accent,c.colors.soft,c.colors.ink].map(color=>'<i style="background:'+color+'"></i>').join('')+'<span>開啟完整設計</span></div></div></a>').join('');
fs.writeFileSync(path.join(root,'index.html'),'<!DOCTYPE html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>10 款登入頁設計｜振興醫院 ESS</title><link rel="stylesheet" href="gallery.css"></head><body><main><header><a href="index.html">振興醫院 <span>LOGIN DESIGN COLLECTION</span></a><span>BOOTSTRAP 5 + JQUERY</span></header><section class="gallery-hero"><div><span class="eyebrow">ONE WORKSPACE. TEN PERSPECTIVES.</span><h1>熟悉的日常，<br>十種新的開始。</h1><p>相同的完整功能，以十種設計語言重新詮釋。<br>從系統識別到登入紀錄，讓每一個入口清楚、有序。</p></div><div class="hero-index" aria-hidden="true">10<span>DESIGN CONCEPTS<br>2026 EDITION</span></div></section><div class="collection-bar"><span>選擇一款，體驗完整登入頁面</span><span>桌面 / 平板 / 手機</span></div><section class="concept-grid" aria-label="10 款設計">'+cards+'</section><section class="requirements"><h2>每一款，都包含完整需求。</h2><div><p><b>帳號與系統識別</b><br>帳號、密碼、忘記與更改密碼連結<br>醒目的系統全名、代碼、環境與版本</p><p><b>公告與維護協助</b><br>全系統／本系統公告、更版內容<br>維護者與聯絡方式、功能教學與說明</p><p><b>裝置與登入紀錄</b><br>電腦名稱、作業系統、瀏覽器<br>最後登入時間、地點與前次使用電腦</p></div></section><footer><span>介面展示 · 登入服務尚未串接，公告與更版為示範資料。</span><span>CHENG HSIN / EMPLOYEE SELF-SERVICE</span></footer></main></body></html>');
fs.writeFileSync(path.join(root,'README.md'),'# 10 款 Bootstrap 5 + jQuery 登入頁\n\n直接開啟 `index.html` 進入設計總覽。每款位於獨立資料夾，內含 Bootstrap 5.3.3 與 jQuery 3.7.1，無 CDN 或遠端字型/圖片依賴。\n\n'+configs.map(c=>'- `'+c.id+'/index.html` — **'+c.name+'**：'+c.description).join('\n')+'\n\n## 完整需求\n\n每款皆包含帳號、密碼、忘記密碼與更改密碼連結；全系統/本系統公告分類與詳情；更版摘要、版本、維護單位、聯絡窗口、電話/分機、電子郵件與教學說明；電腦名稱、作業系統、瀏覽器、最後登入時間與地點及前次使用電腦。\n\n系統名稱、代碼、環境反覆呈現在頁面主標、登入表單與按鈕、頁尾以及瀏覽器分頁標題。\n\n## 設定與正式串接\n\n各款的 `config.js` 是可設定資料。變更 system 可套用其他系統；本系統公告的 systemCode 必須與 system.code 相符。maintainer 可設定實際聯絡人、電話、Email、服務時間；links 可設定正式 HTTPS URL 或站內絕對路徑。未設定時會顯示本機說明視窗。\n\n電腦名稱、最後登入時間/地點與前次電腦名稱須由後端提供，瀏覽器只推測作業系統與瀏覽器。未取得的資料標示「尚未取得／登入後可查看」，聯絡資料標示待維護單位提供。不要把 IP 或瀏覽器的 hostname 當作使用者電腦名稱。\n\n目前表單只檢查欄位，不會送出/儲存帳號密碼或進行真正登入。驗證完成的展示訊息會清空密碼。正式登入與紀錄API尚未串接。\n\n## 開發與預覽\n\n`ten-src/` 為共用原始碼和10款設計設定；執行 `node LoginDemoCode/ten-src/build.cjs` 重新產生各款。會從專案 `LoginDemoCC/assets/libs` 複製既有版本的 Bootstrap/jQuery。`ten-src/verify.cjs` 使用此電腦已安裝的 Playwright 驗證與產生截圖。每款附 `desktop-preview.png`、`mobile-preview.png`。\n\n先前四款設計仍保留於原資料夾，本次總覽只列出新10款。\n');
console.log(JSON.stringify({created:configs.map(c=>c.id)}));
